# Generated by Django 2.2.6 on 2019-11-20 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0003_auto_20191120_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturadet',
            options={'permissions': [('sup_caja_facturadet', 'Permisos de Supervisor de Caja Detalle')], 'verbose_name': 'Detalle Factura', 'verbose_name_plural': 'Detalles Facturas'},
        ),
    ]
